### ISSUE TITLE
license

### ISSUE THREAD

**Issue by rchar01** [DarwinAwardWinner/ido-yes-or-no#3]
Hello, it is a very nice package but I can't find a license file, is it GPL, MIT or something else? It would be good to know.

**Comment by DarwinAwardWinner** [comment]
Consider it GPL2+. I'll add a license to the source when I get a chance.

**Comment by rchar01** [comment]
Thank you

**Comment by DarwinAwardWinner** [comment]
I ended up going with GPL3+ for consistency since that's what I've put my other elisp code under.
